---
title: "Who likes the constitution?"
output: github_document
---

### A qui li agrada la constitució?

```{r setup, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
               fig.path = 'figures/')
```


```{r}
# Libraries
library(vilaweb)
library(rtweet)
library(tidyverse)
library(databrew)
```

```{r, fig.height = 7}
axis_dict <- data_frame(axis = c('Extrema esquerra',
                                 as.character(1:9),
                                 'Extrema dreta'),
                        new_axis = c('Extrema esquerra',
                                     'Extrema esquerra',
                                     'Esquerra',
                                     'Esquerra',
                                     'Centre',
                                     'Centre',
                                     'Centre',
                                     'Dreta',
                                     'Dreta',
                                     'Extrema dreta',
                                     'Extrema dreta')) %>%
  mutate(new_axis = gsub(' ', '\n', new_axis))
plot_data <- 
  vilaweb::ceo %>%
  filter(MES %in% 10:11,
         ANY == 2018) %>%
  dplyr::mutate(axis = P25,
         constitution = P95) %>%
    filter(!axis %in% c('No ho sap', 'No contesta')) %>%
  left_join(axis_dict) %>%
  dplyr::select(-axis) %>%
  dplyr::rename(axis = new_axis) %>%
  mutate(constitution = as.character(constitution)) %>%
  mutate(constitution = ifelse(constitution %in% c('Votaria sí',
                                                    'Votaria no'),
                               constitution,
                               'NS/NC/Nul')) %>%
  group_by(axis, constitution)%>%
  summarise(n = sum(PONDERA)) %>%
  ungroup %>%
  group_by(axis) %>%
  mutate(p = n / sum(n) * 100,
         number = sum(n),
         pp = n / sum(n[constitution != 'NS/NC/Nul']) * 100) %>%
  ungroup
plot_data$constitution <-
  factor(plot_data$constitution,
         levels = rev(c('Votaria sí',
                    'NS/NC/Nul',
                    'Votaria no')))
plot_data$axis <- 
  factor(plot_data$axis,
         levels = c('Extrema\nesquerra',
                   'Esquerra',
                   'Centre',
                   'Dreta',
                   'Extrema\ndreta'))
  
bp <- function(x,z){RColorBrewer::brewer.pal(n = 8,name =x)[z]}
cols <- rev(c(bp('Blues', 5),
          bp('Greys', 2),
          bp('Reds', 5)))
ggplot(data = plot_data,
       aes(x = axis,
           y = p,
           fill = constitution)) +
  geom_bar(stat = 'identity',
           color = 'black',
           lwd = 0.2,
           position = position_stack()) +
  theme_databrew() +
  labs(x = 'Ideologia autoubicada (escala 0-10)',
       y = 'Percentage',
       title = 'Suport de la constitució a Catalunya',
       subtitle = 'Si es tornés a celebrar un referèndum per decidir sobre l’actual\nConstitució espanyola aprovada el 1978, tal com és ara, vostè què faria?',
       caption = 'Dades del Baròmetre d\'Opinió Pública, 3a onada 2018.\nMostra: 1500 residents de Catalunya amb ciutadania espayola. Codificació de categories: escala ideòlogica 0-10:\n0-1=extrema esquerra;2-3=esquerra;4-6=centre;7-8=dreta;9-10=extrema dreta.\nElaboració del gràfic: Joe Brew | @joethebrew.') +
  scale_fill_manual(name = '',
                    values = cols) +
  geom_text(aes(label = round(p, digits = 1)),
            position = position_stack(),
            vjust = 1.4,
            size = 5,
            alpha = 0.6) +
  theme(plot.title = element_text(size = 25),
        plot.subtitle = element_text(size = 13.5),
        axis.text.x = element_text(size = 17),
        axis.text.y = element_text(size = 17),
        legend.text = element_text(size = 20))
x = vilaweb::ceo %>% filter(MES %in% 10:11,
         ANY == 2018) %>% group_by(P95) %>% summarise(n = sum(PONDERA)) %>% ungroup %>% mutate(p = n / sum(n) * 100)
```
