---
title: "Newspapers"
output: github_document
---


```{r setup, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
               fig.path = 'figures/')
```


```{r}
# Libraries
library(vilaweb)
library(rtweet)
library(tidyverse)
library(databrew)
library(qdapRegex)
library(httr)
# devtools::install_github('jayjacobs/tldextract')
library(tldextract)
```

```{r, eval = TRUE}
# Set up
source('get_tweets.R')
```

```{r}




make_keys <- function(x,y){
  return(data_frame(newspaper = x,
                    key = y))
}
# Extract core
# Define the url keys
keys <- 
  list(
    make_keys('La Vanguardia', 'lavanguardia.com'),
    make_keys('El Mundo', 'elmundo.es'),
    make_keys('Telecinco', 'telecinco.es'),
    make_keys('El Diario', 'eldiario.es'),
    make_keys('Huffington Post', 'huffingtonpost.es'),
    make_keys('El Público', 'publico.es'),
    make_keys('El Periódico', 'elperiodico.es'),
    make_keys('Cadana Ser', 'cadenaser.com'),
    make_keys('La Verdad', 'laverdad.es'),
    make_keys('20 Minutos', '20minutos.es')
  )
# Get urls

```